[package]
name = "matrix-stream"
version = "0.1.0"
edition = "2024"

[features]
default = []
raspi = ["rppal"]

[dependencies]
rppal = { version = "0.22.1", optional = true }
image = { version = "0.25.6" }
